# Generated by Django 2.0.13 on 2019-07-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20190625_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='name',
            field=models.CharField(blank=True, help_text='Angabe optional', max_length=25, null=True),
        ),
    ]
