# Generated by Django 2.0.13 on 2019-07-11 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190617_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Classics', 'Classics'), ('Must Haves', 'Must Haves'), ('Trends', 'Trends')], default=django.utils.timezone.now, max_length=100),
        ),
    ]
