# Generated by Django 2.0.13 on 2019-07-11 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190711_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Classics', 'Classics'), ('Must Haves', 'Must Haves'), ('Trends', 'Trends')], default=django.utils.timezone.now, max_length=100),
        ),
    ]
