# Generated by Django 2.0.13 on 2019-07-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190711_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(choices=[('Classics', 'Classics'), ('Must Haves', 'Must Haves'), ('Trends', 'Trends')], on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
