# Generated by Django 2.0.13 on 2019-07-15 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190711_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='Slug bitte identisch zum Name der Category setzen', max_length=100, unique=True),
        ),
    ]
