# Generated by Django 2.0.13 on 2019-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('street_number', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
