# Generated by Django 2.0.13 on 2019-07-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20190715_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',), 'verbose_name': 'Date (Format: tt.mm.jjj)'},
        ),
    ]
