# Generated by Django 2.0.13 on 2019-07-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20190715_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='street_number',
            field=models.CharField(max_length=50, verbose_name='Street and Number'),
        ),
    ]
